apiVersion: v2
name: portfolio-helm-metallb
description: A Helm chart for deploying metallb configuration
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: lgtm-distributed
    alias: lgtm
    version: 2.1.0
    repository: https://grafana.github.io/helm-charts
  - name: minio
    version: 5.4.0
    repository: https://charts.min.io/