lgtm:
  grafana:
    image:
      tag: 12.1.1
    # env:
    #   GF_INSTALL_PLUGINS: grafana-metricsdrilldown-app,grafana-exploretraces-app,grafana-lokiexplore-app
    grafana.ini:
      auth.anonymous:
        enabled: true
        org_role: Viewer
        hide_version: true
  tempo:
    minio:
      enabled: false
    tempo:
      traces:
        otlp:
          grpc:
            enabled: true
      structuredConfig:
        storage:
          trace:
            backend: s3
            s3:
              bucket: tempo-traces
              endpoint: minio.minio.svc.cluster.local:9000
              insecure: true
              access_key: lgtm
              secret_key: minio123
              insecure: true
  mimir:
    minio:
      enabled: false
    ingester:
      replicas: 1
    mimir:
      structuredConfig:
        common:
          storage:
            backend: s3
            s3:
              endpoint: minio.minio.svc.cluster.local:9000
              insecure: true
              access_key_id: lgtm
              secret_access_key: minio123
        blocks_storage:
          s3:
            bucket_name: mimir-tsdb
        alertmanager_storage:
          s3:
            bucket_name: mimir-alertmanager
        ruler_storage:
          s3:
            bucket_name: mimir-ruler