lgtm:
  grafana:
    env:
      GF_INSTALL_PLUGINS: grafana-metricsdrilldown-app,grafana-exploretraces-app,grafana-lokiexplore-app
    grafana.ini:
      auth.anonymous:
        enabled: true
        org_role: Viewer
        hide_version: true
  tempo:
    tempo:
      minio:
        enabled: false
      structuredConfig:
        common:
          storage:
            backend: s3
            s3:
              endpoint: minio.local:9000
              insecure: true
              access_key_id: lgtm
              secret_access_key: minio123
              http:
                insecure_skip_verify: true
  mimir:
    mimir:
      minio:
        enabled: false
      ingester:
        replicas: 1
      structuredConfig:
        common:
          storage:
            backend: s3
            s3:
              endpoint: minio.local:9000
              insecure: true
              access_key_id: lgtm
              secret_access_key: minio123
        blocks_storage:
          s3:
            bucket_name: mimir-tsdb
        alertmanager_storage:
          s3:
            bucket_name: mimir-alertmanager
        ruler_storage:
          s3:
            bucket_name: mimir-ruler

minio:
  replicas: 2
  rootUser: lgtm
  rootPassword: minio123
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  buckets:
  - name: tempo-traces
    policy: none
    purge: false
  - name: mimir-ruler
    policy: none
    purge: false
  - name: mimir-tsdb
    policy: none
    purge: false
  - name: mimir-alertmanager
    policy: none
    purge: false