alloy:
  configMap:
    content: |
      logging {
        level = "INFO"
        format = "logfmt"
      }

      discovery.kubernetes "pods" {
        role = "pod"
      }

      discovery.kubernetes "nodes" {
        role = "node"
      }

      discovery.kubernetes "services" {
        role = "service"
      }

      discovery.kubernetes "endpoints" {
        role = "endpoint"
      }
      
      discovery.kubernetes "endpointslices" {
        role = "endpointslice"
      }

      discovery.kubernetes "ingresses" {
        role = "ingress"
      }

      prometheus.exporter.cadvisor {

      }

      prometheus.scrape "cadvisor" {
        targets    = prometheus.exporter.cadvisor.example.targets
        forward_to = [ prometheus.remote_write.default.receiver ]
      }

      prometheus.remote_write "default" {
        url = "http://lgtm-mimir-distributor.lgtm.svc.cluster.local:8080/api/v1/push"
      }