lgtm:
  grafana:
    image:
      tag: 12.1.1
    env:
      GF_INSTALL_PLUGINS: isovalent-hubble-datasource
    grafana.ini:
      auth.anonymous:
        enabled: true
        org_role: Viewer
        hide_version: true
    dashboards:
      default:
        prometheus-stats:
          gnedId: 445
          revision: 1
          datasource: Mimir
        kubernetes-stats:
          gnedId: 315
          revision: 3
          datasource: Mimir
        argocd-overview:
          gnedId: 19993
          revision: 4
          datasource: Mimir
  tempo:
    rollout_operator:
      enabled: false
    minio:
      enabled: false
    metaMonitoring:
      grafanaAgent:
        installOperator: false
        enabled: false
    ingester:
      replicas: 2
    distributor:
      replicas: 2
      affinity: {} # Disable pod anti-affinity for single node clusters
    traces:
      otlp:
        http:
          enabled: true
    metricsGenerator:
      enabled: true
    tempo:
      structuredConfig:
        storage:
          trace:
            backend: s3
            s3:
              bucket: tempo-traces
              endpoint: minio.minio.svc.cluster.local:9000
              insecure: true
              access_key: lgtm
              secret_key: minio123
              insecure: true
  mimir:
    minio:
      enabled: false
    rollout_operator:
      enabled: false
    metaMonitoring:
      grafanaAgent:
        installOperator: false
        enabled: false
    mimir:
      structuredConfig:
        common:
          storage:
            backend: s3
            s3:
              endpoint: minio.minio.svc.cluster.local:9000
              insecure: true
              access_key_id: lgtm
              secret_access_key: minio123
        blocks_storage:
          s3:
            bucket_name: mimir-tsdb
        alertmanager_storage:
          s3:
            bucket_name: mimir-alertmanager
        ruler_storage:
          s3:
            bucket_name: mimir-ruler