lgtm:
  grafana:
    env:
      GF_INSTALL_PLUGINS: grafana-metricsdrilldown-app,grafana-exploretraces-app,grafana-lokiexplore-app
    # grafana.ini: |
    #   [auth.anonymous]
    #   enabled = true
    #   org_role = Viewer
    #   hide_version = true
  tempo:
    minio:
      mcImage:
        tag: RELEASE.2023-04-06T16-51-10Z # Why does the official chart not use this version?
      buckets:
        - name: tempo-traces
          policy: none
          purge: false
        - name: enterprise-traces
          policy: none
          purge: false
        - name: enterprise-traces-admin
          policy: none
          purge: false
        - name: enterprise-metrics-admin
          policy: none
          purge: false
        - name: mimir-ruler
          policy: none
          purge: false
        - name: mimir-tsdb
          policy: none
          purge: false
  mimir:
    minio:
      rootUser: grafana-tempo
    ingester:
      replicas: 1