alloy:
  alloy:
    configMap:
      content: |
        livedebugging {
          enabled = true
        }

        logging {
          level = "info"
          format = "logfmt"
        }

        discovery.kubernetes "pods" {
          role = "pod"
        }

        discovery.kubernetes "nodes" {
          role = "node"
        }

        discovery.kubernetes "services" {
          role = "service"
        }

        discovery.kubernetes "endpoints" {
          role = "endpoint"
        }
        
        discovery.kubernetes "endpointslices" {
          role = "endpointslice"
        }

        discovery.kubernetes "ingresses" {
          role = "ingress"
        }

        prometheus.exporter.cadvisor "default" {}

        prometheus.scrape "cadvisor" {
          targets    = prometheus.exporter.cadvisor.default.targets
          forward_to = [ prometheus.remote_write.default.receiver ]
        }

        prometheus.scrape "argocd" {
          targets    = [
            {"__address__" = "bootstrap-argocd-application-controller-metrics.argocd.svc.cluster.local:8083", "instance" = "argocd"},
          ]
          forward_to = [ prometheus.remote_write.default.receiver ]
        }

        prometheus.remote_write "default" {
          endpoint {
            url     = "http://lgtm-mimir-distributor.lgtm.svc.cluster.local:8080/api/v1/push"
            headers = {
              "X-Scope-OrgID" = "anonymous",
            }
          }
        }