lgtm:
  grafana:
    env:
      GF_INSTALL_PLUGINS: grafana-metricsdrilldown-app,grafana-exploretraces-app,grafana-lokiexplore-app
    grafana.ini:
      auth.anonymous:
        enabled: true
        org_role: Viewer
        hide_version: true
  tempo:
    minio:
      image:
        tag: RELEASE.2025-07-23T15-54-02Z #
      mcImage:                            # This should work out of the box 
        tag: RELEASE.2025-07-21T05-28-08Z # 
      buckets:
        - name: tempo-traces
          policy: none
          purge: false
        - name: enterprise-traces
          policy: none
          purge: false
        - name: enterprise-traces-admin
          policy: none
          purge: false
        - name: enterprise-metrics-admin
          policy: none
          purge: false
        - name: mimir-ruler
          policy: none
          purge: false
        - name: mimir-tsdb
          policy: none
          purge: false
  mimir:
    minio:
      rootUser: grafana-tempo
      image:
        tag: RELEASE.2025-07-23T15-54-02Z #
      mcImage:                            # This should work out of the box 
        tag: RELEASE.2025-07-21T05-28-08Z # 
    ingester:
      replicas: 1